# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.taskmanagement import GetTaskInfo_Responses, GetTaskStatus_Responses, TaskManagementBase

if TYPE_CHECKING:
    from ..server import Server


class TaskManagementImpl(TaskManagementBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)
        self.tasks = {}

    def GetTaskStatus(self, TaskId: str, *, metadata: MetadataDict) -> GetTaskStatus_Responses:
        if TaskId in self.tasks:
            return GetTaskStatus_Responses(Status=self.tasks[TaskId]['status'])
        return GetTaskStatus_Responses(Status="unknown")

    def GetTaskInfo(self, TaskId: str, *, metadata: MetadataDict) -> GetTaskInfo_Responses:
        if TaskId in self.tasks:
            return GetTaskInfo_Responses(TaskInfo=str(self.tasks[TaskId]))
        return GetTaskInfo_Responses(TaskInfo=f"Task {TaskId} not found")
