# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .feature_implementations.devicemanagement_impl import DeviceManagementImpl
from .feature_implementations.taskmanagement_impl import TaskManagementImpl
from .feature_implementations.temperaturecontroller_impl import TemperatureControllerImpl
from .generated.devicemanagement import DeviceManagementFeature
from .generated.taskmanagement import TaskManagementFeature
from .generated.temperaturecontroller import TemperatureControllerFeature


class Server(SilaServer):
    def __init__(
        self,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        if name is None:
            name = "LabDevice"
        if description is None:
            description = "SiLA2 Lab Automation Device Server"
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="LabAutomation",
            server_version="1.0",
            server_vendor_url="https://aws.amazon.com",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.devicemanagement = DeviceManagementImpl(self)
        self.set_feature_implementation(DeviceManagementFeature, self.devicemanagement)

        self.taskmanagement = TaskManagementImpl(self)
        self.set_feature_implementation(TaskManagementFeature, self.taskmanagement)

        self.temperaturecontroller = TemperatureControllerImpl(self)
        self.set_feature_implementation(TemperatureControllerFeature, self.temperaturecontroller)
